version: "3.3"

services:
  auth-service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth-service
    restart: always
    ports:
      - "2000:2000"
    env_file:
      - ./auth/.env
    environment:
      NODE_ENV: development
      PORT: 2000
      CORS_ORIGIN: "*"
    depends_on:
      - keycloak
    networks:
      - ioak-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    command: mongod --port 27017
    ports:
      - "27016:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ioak-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./keycloak/.env
    networks:
      - ioak-network

  kong:
    container_name: kong-gateway
    build:
      context: ./gateway
    ports:
      - "80:8000"
      - "9443:8443"
      - "8001:8001"
      - "8444:8444"
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
    networks:
      - ioak-network

volumes:
  mongo_data:
  postgres_data:

networks:
  ioak-network:
    external: true
