version: "3.8"

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "2000:2000"
    env_file:
      - .env
    environment:
      NODE_ENV: development
      PORT: 2000
      CORS_ORIGIN: "*"
    depends_on:
      - keycloak
    networks:
      - ioak-net

networks:
  ioak-net:
    external: true
